export const colorVars = {
  background: null,
  text: null,
  primary: null,
  secondary: null,
  white: null,
  border: null,
  hover: null,
  focusRing: null,
  slate900: null,
  slate800: null,
  slate700: null,
  slate600: null,
  slate400: null,
  slate500: null,
  slate100: null,
  slate50: null,
  gray50: null,
  gray900: null,
};
